config/routes.rb
Rails.application.routes.draw do
  root :to => 'static_pages#index', :via => :get

  get 'overview' => 'overview#index', :as => 'overview'
  get 'profile/:id' => 'profile#show', :as => 'profile'

  resources :users, :only => [] do
    post 'follow' => 'following_relationships#create'
    delete 'follow' => 'following_relationships#destroy'
  end

  resources :posts, :only => [:destroy]
  post 'reblog/:id' => 'posts#reblog', :as => 'reblog'

  resources :text_posts, :only => [:new, :create]
  resources :image_posts, :only => [:new, :create]
  resources :video_posts, :only => [:new, :create]
end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed_user, class_name: 'User'
end

app/models/image_post.rb
class ImagePost < ActiveRecord::Base
  has_attached_file :image, :styles => {
    :medium => "300x300>",
    :thumb => "100x100>"
  }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :image, :attachment_presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :postable, polymorphic: true

  validates_associated :postable

  default_scope { order(:created_at => :desc) }
end

app/models/text_post.rb
class TextPost < ActiveRecord::Base
  validates :body, :presence => true
end

app/models/timeline.rb
class Timeline
  include ActiveModel::Model
  extend ActiveModel::Naming

  def initialize(user)
    @user = user
  end

  def posts
    Post.where(user_id: timeline_user_ids)
  end

  private

  def timeline_user_ids
    [@user.id] + @user.followed_user_ids
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :posts

  has_many :followed_user_relationships,
    :foreign_key => :follower_id,
    :class_name => 'FollowingRelationship'
  has_many :followed_users, :through => :followed_user_relationships

  has_many :follower_relationships,
    :foreign_key => :followed_user_id,
    :class_name => 'FollowingRelationship'
  has_many :followers, :through => :follower_relationships

  def following?(user)
    followed_user_ids.include? user.id
  end

  def follow(user)
    followed_users << user
  end

  def unfollow(user)
    followed_users.delete(user)
  end
end

app/models/video_post.rb
class VideoPost < ActiveRecord::Base
  validates :url, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController
  before_action :require_login

  def create
    if current_user.id == user.id
      redirect_to profile_path(user)
    end

    current_user.follow user
    redirect_to profile_path(user), notice: "Now following"
  end

  def destroy
    current_user.unfollow user
    redirect_to profile_path(user), notice: "Unfollowed"
  end

  private
  
  def user
    @_user ||= User.find_by(id: params[:user_id])
  end
end

app/controllers/image_posts_controller.rb
class ImagePostsController < ApplicationController
  def new
  end

  def create
    image_post = current_user.posts.new(postable: build_image_post)

    if image_post.save
      redirect_to overview_path
    else
      flash[:error] = "Image posts require a file!"
      render :new
    end
  end

  private

  def build_image_post
    ImagePost.new(image_post_params)
  end

  def image_post_params
    params.fetch(:image_post, {}).permit(:image)
  end
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController
  before_action :require_login

  def index
    @timeline = Timeline.new(current_user)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login

  def destroy
    post = current_user.posts.find_by(id: params[:id])

    if post.destroy
      redirect_to overview_path
    else
      flash[:error] = "Nope"
      redirect_to overview_path
    end
  end

  def reblog
    dup = Post.find_by(id: params[:id]).dup
    dup.reblogged = true
    dup.original_poster = dup.user_id
    current_user.posts << dup
    redirect_to overview_path
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  layout 'profile'

  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'static'

  def index
    if signed_in?
      redirect_to overview_path
    end
  end
end

app/controllers/text_posts_controller.rb
class TextPostsController < ApplicationController
  def new
  end

  def create
    text_post = current_user.posts.new(postable: build_text_post)

    if text_post.save
      redirect_to overview_path
    else
      flash[:error] = "Text posts require some content!"
      render :action => :new
    end
  end

  private

  def build_text_post
    TextPost.new(text_post_params)
  end

  def text_post_params
    params.require(:text_post).permit(:title, :body)
  end
end

app/controllers/video_posts_controller.rb
class VideoPostsController < ApplicationController
  def new
  end

  def create
    video_post = current_user.posts.new(postable: build_video_post)

    if video_post.save
      redirect_to overview_path
    else
      flash[:error] = "Video posts must have a valid URL!"
      render :action => :new
    end
  end

  private
  
  def build_video_post
    VideoPost.new(video_post_params)
  end
  
  def video_post_params
    params.require(:video_post).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_with_pipeline(renderable_string, filters=[])
    filter_codex = {
      :markdown => HTML::Pipeline::MarkdownFilter,
      :sanitize => HTML::Pipeline::SanitizationFilter,
      :emoji => HTML::Pipeline::EmojiFilter
    }

    pipeline_filters = [filters]
      .flatten
      .collect { |filter| filter_codex[filter] }
      .uniq

    context = {
      :asset_root => "https://a248.e.akamai.net/assets.github.com/images/icons"
    }

    pipeline = HTML::Pipeline.new(pipeline_filters, context)

    pipeline.to_html(renderable_string)
  end

  def embed(youtube_url)
    # swiped from:
    # http://blog.41studio.com/embed-responsive-youtube-video-in-rails-4/
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end

  def reblogged_post?(post)
    post.reblogged?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_link(user)
    found = User.find(user)
    link_to found.email, profile_path(found)
  end
end

app/views/image_posts/_image_post.html.erb
<div class="post post--image">
  <%= render 'posts/post_meta', :post => post_parent %>
  <%= image_tag image_post.image.url, :class => 'post__image' %>
  <%= render 'posts/post_actions', :post => post_parent %>
</div>

app/views/image_posts/new.html.erb
<%= form_for ImagePost.new, :html => { :multipart => true } do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image, :required => true %>
  <hr>
  <%= f.submit "Post" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Fumblr</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <header class="nav-bar">
      <div class="nav-bar__brand">
        <div class="container">
          <h1>Crumblr</h1>
        </div>
      </div>
      <div class="nav-bar__userarea">
        <div class="container">
          <% if signed_in? %>
            <span class="top-kek"><%= current_user.email %></span>
            <%= button_to 'Sign out', sign_out_path, method: :delete, class: "btn" %>
          <% else %>
            <%= link_to 'Sign in', sign_in_path %>
          <% end %>
        </div>
      </div>
    </header>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Fumblr</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash flash--<%= key %>"><%= value %></div>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PolymorphicTumblr</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>


  <div id="flash">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
  </div>

  <%= yield %>

  </body>
</html>

app/views/overview/index.html.erb
<div class="btn-group">
  <%= link_to "Text", new_text_post_path, class: "btn btn--primary" %>
  <%= link_to "Image", new_image_post_path, class: "btn btn--primary"  %>
  <%= link_to "Video", new_video_post_path, class: "btn btn--primary"  %>
</div>
<hr>
<!-- here be dragons -->
<%= render @timeline.posts %>

app/views/posts/_post.html.erb
<%= render post.postable, :post_parent => post  %>

app/views/posts/_post_actions.html.erb
<% if signed_in? %>
  <div class="post__actions">
    <% if post.user_id == current_user.id  %>
      <%= link_to "Delete", post_path(post), :method => :delete %>
    <% else %>
      <%= link_to "Reblog", reblog_path(post), :method => :post, :class => "reblog" %>
    <% end %>
  </div>
<% end %>

app/views/posts/_post_meta.html.erb
<div class="post__meta">
<% if reblogged_post? post %>
  <%= profile_link(post.user_id) %>
  reblogged
  <%= profile_link(post.original_poster) %>
<% else %>
  <%= profile_link(post.user_id) %>
<% end %>
</div>

app/views/static_pages/index.html.erb
    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
    <%= button_to 'Sign out', sign_out_path, method: :delete %>
  <% else %>
    <%= link_to 'Sign up', sign_up_path %>
    <%= link_to 'Sign in', sign_in_path %>
  <% end %>

app/views/text_posts/_text_post.html.erb
<div class="post post--text">
  <%= render 'posts/post_meta', :post => post_parent %>
  <h2 class="post__title"><%= raw render_with_pipeline(text_post.title, :emoji) %></h2>
  <div class="post__body">
    <%= raw render_with_pipeline(text_post.body, [:markdown, :sanitize, :emoji]) %>
  </div>
  <%= render 'posts/post_actions', :post => post_parent %>
</div>

app/views/text_posts/new.html.erb
<h1>New Text Post</h1>
<hr>
<%= form_for(TextPost.new) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <hr>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <hr>
  <%= f.submit "Post" %>
<% end %>

app/views/video_posts/_video_post.html.erb
<div class="post post--video">
  <%= render 'posts/post_meta', :post => post_parent %>
  <div class="post__video"><%= embed(video_post.url) %></div>
  <%= render 'posts/post_actions', :post => post_parent %>
</div>

app/views/video_posts/new.html.erb
<%= form_for VideoPost.new, :html => { :multipart => true } do |f| %>
  <%= f.label :url %>
  <%= f.text_field :url, :required => true %>
  <hr>
  <%= f.submit "Post" %>
<% end %>